### ISSUE TITLE
mods.txt for TMT6, TMT10, TMT11, iTRAQ4, iTRAQ8, and Label Free

### ISSUE THREAD

**Issue by rkimoakbioinformatics** [MSGFPlus/msgfplus#129]
**Describe the question or problem**
I made mods.txt files for TMT6, TMT10, TMT11, iTRAQ4, iTRAQ8, and Label Free experiments. Can anyone check the files and let me know if they are properly made?

**Details**
mods_tmt6.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
229.1629,*,fix,N-term,TMT6plex
229.1629,K,fix,any,TMT6plex
```
mods_tmt10.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
229.1629,*,fix,N-term,TMT10plex
229.1629,K,fix,any,TMT10plex
```
mods_tmt11.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
229.1629,*,fix,N-term,TMT11plex
229.1629,K,fix,any,TMT11plex
```
mods_itraq4.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
144.102063,*,fix,N-term,iTRAQ4plex
144.102063,K,fix,any,iTRAQ4plex
```
mods_itraq8.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
144.102063,*,fix,N-term,iTRAQ8plex
144.102063,K,fix,any,iTRAQ8plex
```
mods_label_free.txt
```
NumMods=3
C2H3N1O1,C,fix,any,Carbamidomethyl
O1,M,opt,any,Oxidation
H-1N-1O1,NQ,opt,any,Deamidated
H-2O-1,E,opt,N-term,Pyro_glu
H-3N-1,Q,opt,N-term,Pyro-glu
```

**Comment by alchemistmatt** [comment]
Go to [http://www.unimod.org](http://www.unimod.org/modifications_list.php?) then click "Login as Guest".  Now search for TMT to learn the official names of the TMT mods.  Repeat for iTRAQ.  You'll find:

|Name|Mass|Notes|
|------|------|------|
|TMT6plex|229.162932|Use this mod mass and mod name for TMT6, TMT10, and TMT11|
|TMTpro|304.207146|Use for 16-plex TMT|
|iTRAQ4plex|144.102063|4-plex iTRAQ|
|iTRAQ8plex|304.205360|8-plex iTRAQ|
|Glu->pyro-Glu|-18.010565|Empirical formula: H(-2) O(-1)|
|Gln->pyro-Glu|-17.026549|Empirical formula: H(-3) N(-1)|

The web page also has the empirical formulas, e.g. H(12) C(4) 13C(3) N 15N O.  Both the iTRAQ mods and the TMT mods have 13C and 15N, which MS-GF+ does not support.  That is why you had to use the monoisotopic mass, instead of the empirical formula.  

Examining what you provided, you need to change from `TMT10plex` to `TMT6plex` and from `TMT11plex` to `TMT6plex`.  Also, your mod mass for 8-plex iTRAQ is incorrect: we use 304.205360 (which is very close to the listed values of 304.205360 and 304.199040).  You should also switch from interim names `Pyro-glu` and `Pyro_glu` to the final names: `Gln->pyro-Glu` and `Glu->pyro-Glu`

I would also advise you to run MS-GF+ using parameter files instead of with these mod files.  For more info, see the [MS-GF+ Documentation](https://msgfplus.github.io/msgfplus/), specifically https://msgfplus.github.io/msgfplus/MSGFPlus.html

The help pages also include a link to [example parameter files](https://github.com/MSGFPlus/msgfplus/tree/master/docs/ParameterFiles), including both TMT and iTRAQ, though our examples don't include the deamidation that you have.  Including that shouldn't hurt anything.  Examples:
* https://github.com/MSGFPlus/msgfplus/blob/master/docs/ParameterFiles/MSGFPlus_Tryp_DynMetOx_Stat_CysAlk_TMT_6Plex_20ppmParTol.txt
* https://github.com/MSGFPlus/msgfplus/blob/master/docs/ParameterFiles/MSGFPlus_PartTryp_DynMetOx_Stat_CysAlk_iTRAQ_8Plex_20ppmParTol.txt

**Comment by rkimoakbioinformatics** [comment]
@alchemistmatt Thank you so much. I am new to MS-GF+ and MS analysis software, so your answer helped me so much!
