### ISSUE TITLE
Problem with MzidToTsvConverter in WSL

### ISSUE THREAD

**Issue by JannikSchneider12** [MSGFPlus/msgfplus#149]
Hey,

I installed msgf+ in WSL and ran the tool on my mgf file. But now when I want to convert it, I am getting this error and I dont know why:

(base) jannik@DELLXPS:~/msgfplus/MzidToTsvConverter$ mono MzidToTsvConverter.exe -mzid /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid

Error: Unrecognized argument name: home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid

Argument parsing failed: Unknown arguments found

Does someone has an idea what could be the problem?

Thanks for your time and help:)

**Comment by FarmGeek4Life** [comment]
Please put the argument in quotes, like "/home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid"
________________________________
From: Jannik Schneider ***@***.***>
Sent: Tuesday, January 9, 2024 3:47:23 AM
To: MSGFPlus/msgfplus ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MSGFPlus/msgfplus] Problem with MzidToTsvConverter in WSL (Issue #149)

Check twice before you click! This email originated from outside PNNL.


Hey,

I installed msgf+ in WSL and ran the tool on my mgf file. But now when I want to convert it, I am getting this error and I dont know why:

(base) ***@***.***:~/msgfplus/MzidToTsvConverter$ mono MzidToTsvConverter.exe -mzid /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid

Error: Unrecognized argument name: home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid

Argument parsing failed: Unknown arguments found

Does someone has an idea what could be the problem?

Thanks for your time and help:)

**Comment by FarmGeek4Life** [comment]
What is happening is the command line parser it uses supports both '-mzid' and '/mzid', and because the path starts with '/' it thinks it's an argument name, not the value, and I hoped the quotes would bypass that but they did not.

Possible options for you to get around this:
change `-mzid /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid` to:
* `-mzid ~/data/consensus_spectra/falcon_run_1_50_conservative.mzid` (linux interprets '~' to mean 'current user's home directory', but I'm not sure if that will work properly with mono)
* `-mzid:/home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid` (the command line parser used supports ':' and '=' as separators between the argument name and value; this is probably the best option)
* `"-mzid /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mzid"` (I think this would work on the same principle as ':' or '=' separators (' ' (space) is also allowed), since the quotes would mean the name and value are passed as a single string, but it definitely looks odd)

**Comment by JannikSchneider12** [comment]
The second option worked for me. Thank you for the explanation and your help
