### ISSUE TITLE
MS-GF+ now requires Java 8?

### ISSUE THREAD

**Issue by hbarsnes** [MSGFPlus/msgfplus#31]
Hi,

Under requirements for MS-GF+ it says "JRE 1.6 or greater", but seems like the latest release actually requires Java 8?

At least we have a user of MS-GF+ via [SearchGUI](https://github.com/compomics/searchgui) where MS-GF+ fails to start when using Java 7: https://github.com/compomics/searchgui/issues/175, while it works fine on my laptop with Java 8.

Are the MS-GF+ requirements outdated or has the Java 8 requirement been added by mistake?

Best regards,
Harald (SearchGUI developer)

**Comment by FarmGeek4Life** [comment]
Well, the updates to require Java 8 were certainly unintentional (they are apparently a side-effect of a dependency update), and we therefore need to update the documentation.

While it would be nice to continue supporting Java 6, the last public update to it was released in April 2013; the last public Java 7 update was released in April 2015. Java 8 and 9 are still getting updates, and Java 10 was just released; I'm expecting to see an issue appear here sometime about issues running with Java 10, since I already had to make changes to support Java 9 without special command-line syntax.
