### ISSUE TITLE
protein decoy pattern parameter 

### ISSUE THREAD

**Issue by ypriverol** [MSGFPlus/msgfplus#58]
Hi @chambm @FarmGeek4Life : 

We are using the following command:

```
Usage: java -Xmx3500M -cp MSGFPlus.jar edu.ucsd.msjava.msdbsearch.BuildSA
	    -d DatabaseFile (*.fasta or *.fa or *.faa; if a directory path, index all FASTA files)
	    [-tda 0/1/2] (0: Target database only, 1: Concatenated target-decoy database only, 2: Both (Default))
	    [-o OutputDir] (Directory to save index files; default is the same as the input file)
```
To create our database index. However, in some cases whe you are using multiple search engines and you want to generate the fasta database with decoys outside MSGF+ (option 0) I still want that MSGF+ recognize the decoy proteins. Do you would be possible to add the decoy pattern in case someone select option `0` and MSGF+ consider those proteins as decoys.

**Comment by alchemistmatt** [comment]
This will require a code change (possibly quite a bit of code); the current version does not support customizing the decoy protein prefix.  I will look into the feasibility of making this change.

**Comment by ypriverol** [comment]
But this means that MSGF+ will need to create the index all every time we perform the search? We are using this command `java -Xmx3500M -cp MSGFPlus.jar edu.ucsd.msjava.msdbsearch.BuildSA` before performing the search to create the index database only once.

**Comment by FarmGeek4Life** [comment]
Okay, I missed that this was referring to BuildSA; the relevant line in the BuildSA code is [here](https://github.com/MSGFPlus/msgfplus/blob/master/src/main/java/edu/ucsd/msjava/msdbsearch/BuildSA.java#L116).

MSGF+ only creates index files if they don't exist or certain bits of information don't match.

**Comment by alchemistmatt** [comment]
Regardless, I have updated the program to support custom-defined decoy protein prefixes.  I will post the new version under Releases when I'm done testing.

**Comment by alchemistmatt** [comment]
Give https://github.com/MSGFPlus/msgfplus/releases/tag/v2019.02.05 a try and let me know of any issues.  When running BuildSA with `-tda 2`, use `-decoy REV ` to have decoy proteins start with `REV_`
Then, when using MSGFPlus.jar, also use `-decoy REV`  so that the .mzID file that it creates properly flags the decoy proteins as starting with `REV_`.  You can use any text you want with `-decoy`

Note that you don't have to run BuildSA by itself; MS-GF+ will create the index files if they are missing for a given .fasta file, then the next time you use that .fasta file with MS-GF+, if the index files exist, they will be re-used.  The index files have some version stamps in them to validate that they match the .fasta file.

**Comment by ypriverol** [comment]
I have tested the present version and it works. I will close this issue.
