### ISSUE TITLE
mzid (tsv) -> idXML

### ISSUE THREAD

**Issue by mash23** [MSGFPlus/msgfplus#61]
Hi everyone, 
I wonder if there is a way to convert the output of the MS-GF+ to '.idXML' file ?

**Comment by FarmGeek4Life** [comment]
OpenMS has an [IdFileConverter tool](https://github.com/OpenMS/OpenMS/blob/develop/src/topp/IDFileConverter.cpp) that will convert the tsv file from MS-GF+ mzid to .idXML ([their own adapter](https://github.com/OpenMS/OpenMS/blob/develop/src/topp/MSGFPlusAdapter.cpp) for using MS-GF+ does it this way). I can't provide any other information for using it, because I never have. Their downloads are available from their [GitHub releases page](https://github.com/OpenMS/OpenMS/releases)
